server:
  port: 8080
# Mybatis
mybatis:
  type-aliases-package: com.example.TeamLotto.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: TeamLotto
  #Postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/team_lotto?currentSchema=public #로컬
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password:  ${POSTGRESQL_PASSWORD}

  #h2 설정
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/testdb
#    username: root
#    password:
